// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/lucidly-home/PolishedClarity.tsx": () => import("../components/mockups/lucidly-home/PolishedClarity.tsx"),
  "./components/mockups/lucidly-home/WarmElevated.tsx": () => import("../components/mockups/lucidly-home/WarmElevated.tsx")
};
